### ISSUE TITLE
[Question] Can I use live update to ban some websites?

### ISSUE THREAD

**Issue by CocosGames** [britzl/liveupdatetest#1]
How to make a filter or something like that to control or find out which client (or HTML5 hosts) has the authority to access the updated content?
How to use pulic/private keys of manifest?
Thanks.

**Comment by britzl** [comment]
> How to make a filter or something like that to control or find out which client (or HTML5 hosts) has the authority to access the updated content?

It sounds like you are asking for ways to domain/site lock a game. You can use LiveUpdate to update a list of approved domains. There are other similar solutions, such as this one by Subsoap:

https://github.com/subsoap/domainlock

Or a local solutions where you have a separate file with valid domains that you bundle with the application. Like this:

```
local M = {}

function M.verify(accepted_domains_filename)
	if not html5 then return true end

	local file = sys.load_resource(accepted_domains_filename or "/custom_resources/domains")
	if not file then
		return true
	end

	local domain = html5.run("window.top.location.hostname")
	for accepted_domain in file:gmatch("[^\r\n]+") do
		if string.find(domain, accepted_domain) then
			return true
		end
	end
	return false
end

return M
```

> How to use public/private keys of manifest?

This is done automatically. When you bundle your game the live update content will be cryptographically signed with your private key and any downloaded content is verified against the public key which will be included in your application. This ensures that the downloaded content hasn't been tampered with.

https://defold.com/manuals/live-update/#generating-keys-for-signing

**Comment by CocosGames** [comment]
Thank you, I tried subsoap's domainlock.
I realize that the allowed domain list is pure text in the archive.
This won't work. I am trying to encrypt domain strings and decrypt them in runtime by binray scripts.
That may work for me.
Thank you for the answer.
